# .yarnrc.yml
patchFolder: "./patches"

#nmMode: hardlinks-local
enableScripts: true
#pnpMode: loose

#globalFolder: "./.yarn/global"
#enableGlobalCache: false
#cacheMigrationMode: always
#cacheFolder: "./.yarn/cache"

#nodeLinker: pnpm

#nmMode: hardlinks-local

nodeLinker: node-modules
#winLinkType: symlinks

# Turn `@example/package` into `@example+package`, then tack on +version.patch
#patchFileNameTemplate: "${name.replace(/\\//g,'+')}+${source.reference}.patch"