require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, podfile_properties['ios.deploymentTarget'] || '12.0'
install! 'cocoapods',
  :deterministic_uuids => false

target 'SphereonWallet' do
  use_expo_modules!

  pod 'expo-dev-menu', path: '../node_modules/expo-dev-menu', :configurations => :debug
  pod 'expo-dev-launcher', path: '../node_modules/expo-dev-launcher', :configurations => :debug
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled] || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Dir.pwd}/.."
  )

  permissions_path = '../node_modules/react-native-permissions/ios'

    pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
#    pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
#    pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
#    pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
    pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
#    pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
#    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
#    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
#    pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
#    pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
#    pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
    pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
#    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
#    pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
#    pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
#    pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
#    pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
#    pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"
    pod 'CatCrypto', :git => 'https://github.com/Sphereon-Opensource/CatCrypto'

  # Uncomment to opt-in to using Flipper
  # Note that if you have use_frameworks! enabled, Flipper will not work
  #
  # if !ENV['CI']
  #   use_flipper!()
  # end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

end
