import SSIAddressIcon from '../../../components/assets/icons/SSIAddressIcon';
import SSIBirthdayIcon from '../../../components/assets/icons/SSIBirthdayIcon';
import SSIBirthplaceIcon from '../../../components/assets/icons/SSIBirthplaceIcon';
import SSIGenderIcon from '../../../components/assets/icons/SSIGenderIcon';
import SSINationalityIcon from '../../../components/assets/icons/SSINationalityIcon';
import SSIPersonIcon from '../../../components/assets/icons/SSIPersonIcon';

type Icon = 'person' | 'gender' | 'birthday' | 'nationality' | 'birthplace' | 'address';

export const InfoSchemaIcons = {
  person: <SSIPersonIcon width={20} height={20} color="white" />,
  gender: <SSIGenderIcon width={22} height={22} color="white" />,
  birthday: <SSIBirthdayIcon width={20} height={20} color="white" />,
  birthplace: <SSIBirthplaceIcon width={22} height={22} color="white" />,
  address: <SSIAddressIcon width={22} height={22} color="white" />,
  nationality: <SSINationalityIcon width={20} height={20} color="white" />,
} satisfies {[key in Icon]: React.ReactNode};

export type AusweisRequestedInfoItem = {
  label: string;
  icon: Icon;
  data?: string;
};

type Keys =
  | 'given_name'
  | 'family_name'
  | 'birth_family_name'
  | 'birthdate'
  | 'age_in_years'
  | 'age_birth_year'
  | 'place_of_birth'
  | 'nationalities'
  | 'street_address'
  | 'postal_code'
  | 'locality'
  | 'country'
  | 'gender';

export type MappableKeys = Keys | string;
export const keyMappings: {
  [key: MappableKeys]: any;
} = {
  given_name: 'Given name',
  family_name: 'Family name',
  birth_family_name: 'Birth family name',
  age_birth_year: 'Birth year',
  age_in_years: 'Age',
  gender: 'Gender',
  birthdate: 'Date of birth',
  place_of_birth: 'Place of birth',
  nationalities: 'Nationalities',
  address: 'Address',
};

export const IconMap: {
  [key: MappableKeys]: Icon;
} = {
  given_name: 'person',
  family_name: 'person',
  birth_family_name: 'person',
  gender: 'gender',
  birthdate: 'birthday',
  place_of_birth: 'birthplace',
  nationalities: 'nationality',
  age_in_years: 'person',
  age_birth_year: 'birthday',
  address: 'address',
} as const;

export const AusweisRequestedInfoSchema: AusweisRequestedInfoItem[] = Object.keys(keyMappings).map(key => ({
  label: keyMappings[key],
  icon: IconMap[key],
}));

export const PIDCredentialsMock = [
  {
    uniformCredential: {
      type: ['urn:eu.europa.ec.eudi:pid:1'],
      '@context': [],
      credentialSubject: {
        '12': true,
        '14': true,
        '16': true,
        '18': true,
        '21': true,
        '65': false,
        family_name: 'MUSTERMANN',
        given_name: 'ERIKA',
        birthdate: '1984-01-26',
        age_birth_year: 1984,
        age_in_years: 40,
        birth_family_name: 'GABLER',
        nationalities: ['DE'],
        locality: 'KÖLN',
        country: 'DE',
        postal_code: '51147',
        street_address: 'HEIDESTRASSE 17',
      },
      issuanceDate: '2024-08-23T11:26:41Z',
      expirationDate: '2024-09-06T11:26:41Z',
      issuer: 'https://demo.pid-issuer.bundesdruckerei.de/c',
      cnf: {
        jwk: {
          kty: 'EC',
          crv: 'P-256',
          kid: '-NzH-d_eYve3MvVg0xfFPGe1QyCSHO77nzywEAebr40',
          x: 'alNsfaLkpueZD6JS1dxkZZccIDreOAL0tnfJaJDDv6Y',
          y: 'HvTQC7bEs7h9puKAh8C-d3i2GCGivXJC85gom0gFFVs',
          alg: 'ES256',
        },
      },
      proof: {
        type: 'SdJwtProof2024',
        created: '2024-08-23T11:26:41Z',
        proofPurpose: 'authentication',
        verificationMethod: 'https://demo.pid-issuer.bundesdruckerei.de/c',
        jwt: 'eyJ4NWMiOlsiTUlJQ2REQ0NBaHVnQXdJQkFnSUJBakFLQmdncWhrak9QUVFEQWpDQmlERUxNQWtHQTFVRUJoTUNSRVV4RHpBTkJnTlZCQWNNQmtKbGNteHBiakVkTUJzR0ExVUVDZ3dVUW5WdVpHVnpaSEoxWTJ0bGNtVnBJRWR0WWtneEVUQVBCZ05WQkFzTUNGUWdRMU1nU1VSRk1UWXdOQVlEVlFRRERDMVRVRkpKVGtRZ1JuVnVhMlVnUlZWRVNTQlhZV3hzWlhRZ1VISnZkRzkwZVhCbElFbHpjM1ZwYm1jZ1EwRXdIaGNOTWpRd05UTXhNRGd4TXpFM1doY05NalV3TnpBMU1EZ3hNekUzV2pCc01Rc3dDUVlEVlFRR0V3SkVSVEVkTUJzR0ExVUVDZ3dVUW5WdVpHVnpaSEoxWTJ0bGNtVnBJRWR0WWtneENqQUlCZ05WQkFzTUFVa3hNakF3QmdOVkJBTU1LVk5RVWtsT1JDQkdkVzVyWlNCRlZVUkpJRmRoYkd4bGRDQlFjbTkwYjNSNWNHVWdTWE56ZFdWeU1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRU9GQnE0WU1LZzR3NWZUaWZzeXR3QnVKZi83RTdWaFJQWGlObTUyUzNxMUVUSWdCZFh5REsza1Z4R3hnZUhQaXZMUDN1dU12UzZpREVjN3FNeG12ZHVLT0JrRENCalRBZEJnTlZIUTRFRmdRVWlQaENrTEVyRFhQTFcyL0owV1ZlZ2h5dyttSXdEQVlEVlIwVEFRSC9CQUl3QURBT0JnTlZIUThCQWY4RUJBTUNCNEF3TFFZRFZSMFJCQ1l3SklJaVpHVnRieTV3YVdRdGFYTnpkV1Z5TG1KMWJtUmxjMlJ5ZFdOclpYSmxhUzVrWlRBZkJnTlZIU01FR0RBV2dCVFVWaGpBaVRqb0RsaUVHTWwyWXIrcnU4V1F2akFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFiZjVUemtjUXpoZldvSW95aTFWTjdkOEk5QnNGS20xTVdsdVJwaDJieUdRSWdLWWtkck5mMnhYUGpWU2JqVy9VLzVTNXZBRUM1WHhjT2FudXNPQnJvQmJVPSIsIk1JSUNlVENDQWlDZ0F3SUJBZ0lVQjVFOVFWWnRtVVljRHRDaktCL0gzVlF2NzJnd0NnWUlLb1pJemowRUF3SXdnWWd4Q3pBSkJnTlZCQVlUQWtSRk1ROHdEUVlEVlFRSERBWkNaWEpzYVc0eEhUQWJCZ05WQkFvTUZFSjFibVJsYzJSeWRXTnJaWEpsYVNCSGJXSklNUkV3RHdZRFZRUUxEQWhVSUVOVElFbEVSVEUyTURRR0ExVUVBd3d0VTFCU1NVNUVJRVoxYm10bElFVlZSRWtnVjJGc2JHVjBJRkJ5YjNSdmRIbHdaU0JKYzNOMWFXNW5JRU5CTUI0WERUSTBNRFV6TVRBMk5EZ3dPVm9YRFRNME1EVXlPVEEyTkRnd09Wb3dnWWd4Q3pBSkJnTlZCQVlUQWtSRk1ROHdEUVlEVlFRSERBWkNaWEpzYVc0eEhUQWJCZ05WQkFvTUZFSjFibVJsYzJSeWRXTnJaWEpsYVNCSGJXSklNUkV3RHdZRFZRUUxEQWhVSUVOVElFbEVSVEUyTURRR0ExVUVBd3d0VTFCU1NVNUVJRVoxYm10bElFVlZSRWtnVjJGc2JHVjBJRkJ5YjNSdmRIbHdaU0JKYzNOMWFXNW5JRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFWUd6ZHdGRG5jNytLbjVpYkF2Q09NOGtlNzdWUXhxZk1jd1pMOElhSUErV0NST2NDZm1ZL2dpSDkycU1ydTVwL2t5T2l2RTBSQy9JYmRNT052RG9VeWFObU1HUXdIUVlEVlIwT0JCWUVGTlJXR01DSk9PZ09XSVFZeVhaaXY2dTd4WkMrTUI4R0ExVWRJd1FZTUJhQUZOUldHTUNKT09nT1dJUVl5WFppdjZ1N3haQytNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUF3RGdZRFZSMFBBUUgvQkFRREFnR0dNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJR0VtN3drWktIdC9hdGI0TWRGblhXNnlybndNVVQydTEzNmdkdGwxMFk2aEFpQnVURnF2Vll0aDFyYnh6Q1AweFdaSG1RSzlrVnl4bjhHUGZYMjdFSXp6c3c9PSJdLCJraWQiOiJNSUdVTUlHT3BJR0xNSUdJTVFzd0NRWURWUVFHRXdKRVJURVBNQTBHQTFVRUJ3d0dRbVZ5YkdsdU1SMHdHd1lEVlFRS0RCUkNkVzVrWlhOa2NuVmphMlZ5WldrZ1IyMWlTREVSTUE4R0ExVUVDd3dJVkNCRFV5QkpSRVV4TmpBMEJnTlZCQU1NTFZOUVVrbE9SQ0JHZFc1clpTQkZWVVJKSUZkaGJHeGxkQ0JRY205MGIzUjVjR1VnU1hOemRXbHVaeUJEUVFJQkFnPT0iLCJ0eXAiOiJ2YytzZC1qd3QiLCJhbGciOiJFUzI1NiJ9.eyJwbGFjZV9vZl9iaXJ0aCI6eyJfc2QiOlsiQ0VGaVUtWG9ZajEtczVsUUt4cmhWbHZ1QlVOUWMyZldzM29tRE5XcmxGRSJdfSwiX3NkIjpbIktlenpuQnpkbzE3eTZMc0FFRnVhNmQtQkpQVzBaT21IV2JIZkNON2I1eVUiLCJQMXVQU1Bnd1EycjFFTDdXWVNzU3VTSExFRU1fekFISnMtam1pUkUtTE9ZIiwiWGdBRmh3dld2WkVZSll0YkxXY3U5ZWY4ZUlsMzFfN1gyejVPd1pvTFZLdyIsImRBZU9lQmV3T2JyYUhxaTdnamdQalgtc1ROQjVzRG5lSTUyUzE5blBFRVEiLCJmUFUyZDBmcldqZHFtVGxHSTRGRFRaMXoxY2xOMS1wVWhqdlZadTYwTW9vIiwiaGF3cmJEd19MOC05Nlc3aTREVGFGLXZVM3BVTjFDXzBHMWVPR0RIaXFsQSIsIm1RRjlmcElBOHIyS2UwV3dTQ2Z3T1czS3JtUEpmWl9LNS1xMktNUU1tT1kiXSwiYWRkcmVzcyI6eyJfc2QiOlsiLWs4UnE2Y3FxZVpvampRT3YzLV9sOXVhUjROWXpiZjV5dG54bHI3NTlZSSIsIjVRMDZQX292dmhvelAtdXBQaTBnemZaWEpDNHRHR2E3Yi1Tc2t1Q0k1SDQiLCJUN2FuWlhEVm1paW5ycTNVRTdRTS1UcUU5bXhqa0ZTcTk0VkY3aFZMcWlvIiwiaDdSb0haNDA0N2sycWR6MnVycENuZlBONEhUX1FPT0IzTzZkQS1KRVg2dyJdfSwiaXNzdWluZ19jb3VudHJ5IjoiREUiLCJ2Y3QiOiJ1cm46ZXUuZXVyb3BhLmVjLmV1ZGk6cGlkOjEiLCJpc3N1aW5nX2F1dGhvcml0eSI6IkRFIiwiX3NkX2FsZyI6InNoYS0yNTYiLCJpc3MiOiJodHRwczovL2RlbW8ucGlkLWlzc3Vlci5idW5kZXNkcnVja2VyZWkuZGUvYyIsImNuZiI6eyJqd2siOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsImtpZCI6Ii1OekgtZF9lWXZlM012VmcweGZGUEdlMVF5Q1NITzc3bnp5d0VBZWJyNDAiLCJ4IjoiYWxOc2ZhTGtwdWVaRDZKUzFkeGtaWmNjSURyZU9BTDB0bmZKYUpERHY2WSIsInkiOiJIdlRRQzdiRXM3aDlwdUtBaDhDLWQzaTJHQ0dpdlhKQzg1Z29tMGdGRlZzIiwiYWxnIjoiRVMyNTYifX0sImV4cCI6MTcyNTYyMjAwMSwiaWF0IjoxNzI0NDEyNDAxLCJhZ2VfZXF1YWxfb3Jfb3ZlciI6eyJfc2QiOlsiLURNVDVObUpySHBWNHBwZk5OTi1qdlUtN1d0WUZPSDdRal9pMmRhUXNvNCIsIkRGdFIyTFZkV213MG9TN0sxUnRrR3Y0anJYdTYxQ3NZNFpjZTYtYmk1V1UiLCJLUHdNX1FvTFNBMVJIQTNfMFYzdWRST2MwMkdJRmJRMkFsWldWWllfMXNBIiwibFhjUGV4ZUVTeDR3UDBsMXRkVmctSFdkYXJmTTdMdWpKTkx1djZMdXR4NCIsInFMaWZqVnRwbWxzYTVTelhwMmtyQmhuZlJrbmlFbW91V19WXzk1dWdCblEiLCJ3VFdjLTZ1eEtNRGswY0l2cU5UM25Ic3RCU2p0MS1CNGlwVk9GSVowbXRRIl19fQ.TzQW9U2GlnIb4l2WZ76a5JmkAUWCAXMWco1c1xSrMtbZeRoRYkNQZ2k3K288LQjVBz5o7upkhD31wpg6Cqy5Rw~WyJmT2lJV2NWdVdCSDJGZm03ZU52MVVnIiwiZmFtaWx5X25hbWUiLCJNVVNURVJNQU5OIl0~WyJpSjBmdkJ1R3gyZ2k3bHVadjhhQndRIiwiZ2l2ZW5fbmFtZSIsIkVSSUtBIl0~WyJJT3dxaGZLbGgyWEZWS05Qd2FWTjlRIiwiYmlydGhkYXRlIiwiMTk4NC0wMS0yNiJd~WyJCZGtHVnZBc3BBckltYnJRekZaaW5RIiwiYWdlX2JpcnRoX3llYXIiLDE5ODRd~WyJCZGEwTGQ0QVBVTFZEdW94dzRidk5BIiwiYWdlX2luX3llYXJzIiw0MF0~WyJpQV81SlpJSF96V1FScWU1SHZXOHVnIiwiYmlydGhfZmFtaWx5X25hbWUiLCJHQUJMRVIiXQ~WyIwREhsNG1GM2sxS04wUWZBVXZkY25RIiwibmF0aW9uYWxpdGllcyIsWyJERSJdXQ~WyJfZHh1cFQ5ZENDQ3hmcVB1ZmR1UExBIiwiMTIiLHRydWVd~WyJlaWUyNjctUGJDTHRXb3FVNjNEZTFnIiwiMTQiLHRydWVd~WyJUXzE5cFdKMDVzMXRTc0R6M0RaOUxBIiwiMTYiLHRydWVd~WyJ3RTNURlplMkVJQ1p3MHlHaVI2MGV3IiwiMTgiLHRydWVd~WyJPSzhSWXhiLUNaX0REbXkzV1p5N1pRIiwiMjEiLHRydWVd~WyJHZFJKbDVEOS1iTDRRaHlMTG03UnlnIiwiNjUiLGZhbHNlXQ~WyJKU2FqQjVTTm9OaERUQUJtZGZEUm5BIiwibG9jYWxpdHkiLCJCRVJMSU4iXQ~WyJSWFgyUTBGek1tMlkxTWswMTBSQ0FnIiwibG9jYWxpdHkiLCJLw5ZMTiJd~WyJVWFFXNFdYRS1vS1liamppNVZaRG9RIiwiY291bnRyeSIsIkRFIl0~WyJrVmZZZmZCQnFaenA5VXZvdGVJSGlRIiwicG9zdGFsX2NvZGUiLCI1MTE0NyJd~WyJWNjQzSGJZeW9QVFZuanFuVWg5NFRRIiwic3RyZWV0X2FkZHJlc3MiLCJIRUlERVNUUkFTU0UgMTciXQ~',
      },
    },
    rawCredential:
      'eyJ4NWMiOlsiTUlJQ2REQ0NBaHVnQXdJQkFnSUJBakFLQmdncWhrak9QUVFEQWpDQmlERUxNQWtHQTFVRUJoTUNSRVV4RHpBTkJnTlZCQWNNQmtKbGNteHBiakVkTUJzR0ExVUVDZ3dVUW5WdVpHVnpaSEoxWTJ0bGNtVnBJRWR0WWtneEVUQVBCZ05WQkFzTUNGUWdRMU1nU1VSRk1UWXdOQVlEVlFRRERDMVRVRkpKVGtRZ1JuVnVhMlVnUlZWRVNTQlhZV3hzWlhRZ1VISnZkRzkwZVhCbElFbHpjM1ZwYm1jZ1EwRXdIaGNOTWpRd05UTXhNRGd4TXpFM1doY05NalV3TnpBMU1EZ3hNekUzV2pCc01Rc3dDUVlEVlFRR0V3SkVSVEVkTUJzR0ExVUVDZ3dVUW5WdVpHVnpaSEoxWTJ0bGNtVnBJRWR0WWtneENqQUlCZ05WQkFzTUFVa3hNakF3QmdOVkJBTU1LVk5RVWtsT1JDQkdkVzVyWlNCRlZVUkpJRmRoYkd4bGRDQlFjbTkwYjNSNWNHVWdTWE56ZFdWeU1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRU9GQnE0WU1LZzR3NWZUaWZzeXR3QnVKZi83RTdWaFJQWGlObTUyUzNxMUVUSWdCZFh5REsza1Z4R3hnZUhQaXZMUDN1dU12UzZpREVjN3FNeG12ZHVLT0JrRENCalRBZEJnTlZIUTRFRmdRVWlQaENrTEVyRFhQTFcyL0owV1ZlZ2h5dyttSXdEQVlEVlIwVEFRSC9CQUl3QURBT0JnTlZIUThCQWY4RUJBTUNCNEF3TFFZRFZSMFJCQ1l3SklJaVpHVnRieTV3YVdRdGFYTnpkV1Z5TG1KMWJtUmxjMlJ5ZFdOclpYSmxhUzVrWlRBZkJnTlZIU01FR0RBV2dCVFVWaGpBaVRqb0RsaUVHTWwyWXIrcnU4V1F2akFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFiZjVUemtjUXpoZldvSW95aTFWTjdkOEk5QnNGS20xTVdsdVJwaDJieUdRSWdLWWtkck5mMnhYUGpWU2JqVy9VLzVTNXZBRUM1WHhjT2FudXNPQnJvQmJVPSIsIk1JSUNlVENDQWlDZ0F3SUJBZ0lVQjVFOVFWWnRtVVljRHRDaktCL0gzVlF2NzJnd0NnWUlLb1pJemowRUF3SXdnWWd4Q3pBSkJnTlZCQVlUQWtSRk1ROHdEUVlEVlFRSERBWkNaWEpzYVc0eEhUQWJCZ05WQkFvTUZFSjFibVJsYzJSeWRXTnJaWEpsYVNCSGJXSklNUkV3RHdZRFZRUUxEQWhVSUVOVElFbEVSVEUyTURRR0ExVUVBd3d0VTFCU1NVNUVJRVoxYm10bElFVlZSRWtnVjJGc2JHVjBJRkJ5YjNSdmRIbHdaU0JKYzNOMWFXNW5JRU5CTUI0WERUSTBNRFV6TVRBMk5EZ3dPVm9YRFRNME1EVXlPVEEyTkRnd09Wb3dnWWd4Q3pBSkJnTlZCQVlUQWtSRk1ROHdEUVlEVlFRSERBWkNaWEpzYVc0eEhUQWJCZ05WQkFvTUZFSjFibVJsYzJSeWRXTnJaWEpsYVNCSGJXSklNUkV3RHdZRFZRUUxEQWhVSUVOVElFbEVSVEUyTURRR0ExVUVBd3d0VTFCU1NVNUVJRVoxYm10bElFVlZSRWtnVjJGc2JHVjBJRkJ5YjNSdmRIbHdaU0JKYzNOMWFXNW5JRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFWUd6ZHdGRG5jNytLbjVpYkF2Q09NOGtlNzdWUXhxZk1jd1pMOElhSUErV0NST2NDZm1ZL2dpSDkycU1ydTVwL2t5T2l2RTBSQy9JYmRNT052RG9VeWFObU1HUXdIUVlEVlIwT0JCWUVGTlJXR01DSk9PZ09XSVFZeVhaaXY2dTd4WkMrTUI4R0ExVWRJd1FZTUJhQUZOUldHTUNKT09nT1dJUVl5WFppdjZ1N3haQytNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUF3RGdZRFZSMFBBUUgvQkFRREFnR0dNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJR0VtN3drWktIdC9hdGI0TWRGblhXNnlybndNVVQydTEzNmdkdGwxMFk2aEFpQnVURnF2Vll0aDFyYnh6Q1AweFdaSG1RSzlrVnl4bjhHUGZYMjdFSXp6c3c9PSJdLCJraWQiOiJNSUdVTUlHT3BJR0xNSUdJTVFzd0NRWURWUVFHRXdKRVJURVBNQTBHQTFVRUJ3d0dRbVZ5YkdsdU1SMHdHd1lEVlFRS0RCUkNkVzVrWlhOa2NuVmphMlZ5WldrZ1IyMWlTREVSTUE4R0ExVUVDd3dJVkNCRFV5QkpSRVV4TmpBMEJnTlZCQU1NTFZOUVVrbE9SQ0JHZFc1clpTQkZWVVJKSUZkaGJHeGxkQ0JRY205MGIzUjVjR1VnU1hOemRXbHVaeUJEUVFJQkFnPT0iLCJ0eXAiOiJ2YytzZC1qd3QiLCJhbGciOiJFUzI1NiJ9.eyJwbGFjZV9vZl9iaXJ0aCI6eyJfc2QiOlsiQ0VGaVUtWG9ZajEtczVsUUt4cmhWbHZ1QlVOUWMyZldzM29tRE5XcmxGRSJdfSwiX3NkIjpbIktlenpuQnpkbzE3eTZMc0FFRnVhNmQtQkpQVzBaT21IV2JIZkNON2I1eVUiLCJQMXVQU1Bnd1EycjFFTDdXWVNzU3VTSExFRU1fekFISnMtam1pUkUtTE9ZIiwiWGdBRmh3dld2WkVZSll0YkxXY3U5ZWY4ZUlsMzFfN1gyejVPd1pvTFZLdyIsImRBZU9l.TzQW9U2GlnIb4l2WZ76a5JmkAUWCAXMWco1c1xSrMtbZeRoRYkNQZ2k3K288LQjVBz5o7upkhD31wpg6Cqy5Rw~WyJmT2lJV2NWdVdCSDJGZm03ZU52MVVnIiwiZmFtaWx5X25hbWUiLCJNVVNURVJNQU5OIl0~WyJpSjBmdkJ1R3gyZ2k3bHVadjhhQndRIiwiZ2l2ZW5fbmFtZSIsIkVSSUtBIl0~WyJJT3dxaGZLbGgyWEZWS05Qd2FWTjlRIiwiYmlydGhkYXRlIiwiMTk4NC0wMS0yNiJd~WyJCZGtHVnZBc3BBckltYnJRekZaaW5RIiwiYWdlX2JpcnRoX3llYXIiLDE5ODRd~WyJCZGEwTGQ0QVBVTFZEdW94dzRidk5BIiwiYWdlX2luX3llYXJzIiw0MF0~WyJpQV81SlpJSF96V1FScWU1SHZXOHVnIiwiYmlydGhfZmFtaWx5X25hbWUiLCJHQUJMRVIiXQ~WyIwREhsNG1GM2sxS04wUWZBVXZkY25RIiwibmF0aW9uYWxpdGllcyIsWyJERSJdXQ~WyJfZHh1cFQ5ZENDQ3hmcVB1ZmR1UExBIiwiMTIiLHRydWVd~WyJlaWUyNjctUGJDTHRXb3FVNjNEZTFnIiwiMTQiLHRydWVd~WyJUXzE5cFdKMDVzMXRTc0R6M0RaOUxBIiwiMTYiLHRydWVd~WyJ3RTNURlplMkVJQ1p3MHlHaVI2MGV3IiwiMTgiLHRydWVd~WyJPSzhSWXhiLUNaX0REbXkzV1p5N1pRIiwiMjEiLHRydWVd~WyJHZFJKbDVEOS1iTDRRaHlMTG03UnlnIiwiNjUiLGZhbHNlXQ~WyJKU2FqQjVTTm9OaERUQUJtZGZEUm5BIiwibG9jYWxpdHkiLCJCRVJMSU4iXQ~WyJSWFgyUTBGek1tMlkxTWswMTBSQ0FnIiwibG9jYWxpdHkiLCJLw5ZMTiJd~WyJVWFFXNFdYRS1vS1liamppNVZaRG9RIiwiY291bnRyeSIsIkRFIl0~WyJrVmZZZmZCQnFaenA5VXZvdGVJSGlRIiwicG9zdGFsX2NvZGUiLCI1MTE0NyJd~WyJWNjQzSGJZeW9QVFZuanFuVWg5NFRRIiwic3RyZWV0X2FkZHJlc3MiLCJIRUlERVNUUkFTU0UgMTciXQ~',
  },
];
